#+TITLE: gmpl-mode
Major mode for editing GMPL(MathProg) files.

* Overview
  GMPL is a modeling language to create mathematical programming models which
  can be used by [[https://www.gnu.org/software/glpk/][GLPK]].

  Although GMPL is a subset of AMPL, the current Emacs major mode for AMPL,
  which can be found at https://github.com/dpo/ampl-mode, doesn't work well with
  GMPL files. Here is the list of the reasons why =gmpl-mode= works better
  compared to =ampl-mode= when editing GMPL files:
  1. Support single quoted string and C style comments.
  2. Some keywords(such as =for=, =end=) are highlighted properly, and it
     provides better hightlighting generally.
  3. A usable indent function.

* Usage
  First, add the =load-path= and load the file:
  : (add-to-list 'load-path "/path/to/gmpl-mode.el")
  : (require 'gmpl-mode)

  Use =gmpl-mode= when editing files with the =.mod= extension:
  : (add-to-list 'auto-mode-alist '("\\.mod\\'" . gmpl-mode))

* *TODO*
  - Add some functions to interact with the =glpsol= command line tool.
  - Translate LaTeX equations to GMPL format and solve the problem directly.
  - Add company-keywords support.
